"""Added adj_close column to StockPoint table

Revision ID: 1e51050924ca
Revises: 2985aa92157f
Create Date: 2014-10-29 18:35:07.567040

"""

# revision identifiers, used by Alembic.
revision = '1e51050924ca'
down_revision = '2985aa92157f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_point', sa.Column('adj_close', sa.Float(precision=2, asdecimal=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_point', 'adj_close')
    ### end Alembic commands ###
