"""initial_revision

Revision ID: 2985aa92157f
Revises: None
Create Date: 2014-10-25 18:17:45.104531

"""

# revision identifiers, used by Alembic.
revision = '2985aa92157f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('high', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('low', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('close', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('rsi', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('macd', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.Column('macd_signal', sa.Float(precision=2, asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_point')
    op.drop_table('stock')
    ### end Alembic commands ###
