"""52 week high low avg volume

Revision ID: 46841d7388e4
Revises: 43ad0587fb73
Create Date: 2014-11-20 17:10:41.019286

"""

# revision identifiers, used by Alembic.
revision = '46841d7388e4'
down_revision = '43ad0587fb73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_point', sa.Column('avg_volume_3_months', sa.Integer(), nullable=True))
    op.add_column('stock_point', sa.Column('high_52_weeks', sa.Float(precision=2, asdecimal=True), nullable=True))
    op.add_column('stock_point', sa.Column('low_52_weeks', sa.Float(precision=2, asdecimal=True), nullable=True))
    op.add_column('stock_point', sa.Column('sma_50', sa.Float(precision=2, asdecimal=True), nullable=True))
    op.add_column('stock_point', sa.Column('sma_200', sa.Float(precision=2, asdecimal=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_point', 'avg_volume_3_months')
    op.drop_column('stock_point', 'high_52_weeks')
    op.drop_column('stock_point', 'low_52_weeks')
    op.drop_column('stock_point', 'sma_50')
    op.drop_column('stock_point', 'sma_200')
    ### end Alembic commands ###
